spring:
  redis:
    database: 0
    host: 192.168.1.134
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 5
        min-idle: 1
    timeout: 1000