server:
  port: 8662

spring:
  zipkin:
    base-url: http://127.0.0.1:9411
  application:
    name: service-hi

eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/
      #defaultZone: http://127.0.0.1:8761/eureka/